
import React from 'react';
import { 
  BookOpen, 
  Star, 
  Clock, 
  RotateCcw, 
  ClipboardList, 
  TrendingUp, 
  Plus,
  X,
  ChevronRight,
  MoreHorizontal,
  PenLine,
  LayoutGrid,
  Sparkles,
  Trash2,
  Check,
  Bold,
  Image as ImageIcon,
  List as ListIcon,
  CheckSquare,
  Hash,
  Plane,
  Highlighter,
  Calendar,
  Shuffle,
  History,
  StickyNote,
  CalendarDays,
  ChevronLeft,
  ChevronUp,
  ChevronDown,
  Settings,
  Copy,
  Upload,
  Download,
  Palette,
  RefreshCw
} from 'lucide-react';

export const Icons = {
  List: BookOpen,
  Rating: Star,
  Countdown: Clock,
  LastDone: RotateCcw,
  SOP: ClipboardList, // Keep SOP icon for Plan, or change to ClipboardList
  Plan: CalendarDays,
  Data: TrendingUp,
  NoteWidget: StickyNote,
  Plus,
  Close: X,
  ArrowRight: ChevronRight,
  ArrowLeft: ChevronLeft,
  ChevronLeft,
  ChevronUp,
  ChevronDown,
  More: MoreHorizontal,
  Note: PenLine,
  Dashboard: LayoutGrid,
  AI: Sparkles,
  Delete: Trash2,
  Check: Check,
  Bold,
  Image: ImageIcon,
  ListIcon,
  CheckSquare,
  Hash,
  Plane,
  Highlight: Highlighter,
  Calendar,
  Shuffle,
  RotateCcw,
  TrendingUp,
  History,
  Settings,
  Copy,
  Upload,
  Download,
  Palette,
  Refresh: RefreshCw
};
